### ISSUE TITLE
Error on create new chat

### ISSUE THREAD

**Issue by RyzerZ** [bitswired/ai-chat-app#3]
"On Ai CHAT's chat page, the 'create new chat' button does not appear when there is no active chat present."

**Comment by jimzer** [comment]
Hey @RyzerZ!
Thank you for raising the issue.
I hope you like the app :)

I pushed a new major version with lots of improvements.
I added the button to create the chat on the Chat page and I fixed the issue in the home page.

**Be careful, you now have to add your API key in the /settings page.**

The new features are:

👉🏽 Import & create templates
👉🏽 Create Powerful Smart templates
👉🏽 Dark Mode
👉🏽 Render Markdown
👉🏽 Refreshed UI Design

I updated the video in the README to introduce the new changes.

Let me know if the problem is solved :).

**Comment by specked** [comment]
@jimzer 

I still get this error after submitted text to a chat: 

![image](https://user-images.githubusercontent.com/1870392/223425778-1ee23d3e-b87d-4c6e-8f73-7e12c85fa364.png)

**Comment by RyzerZ** [comment]
> 

Now it's working fine! God job man!

**Comment by jimzer** [comment]
Is it possible for you to run the app in development mode.
`yarn dev` instead of `yarn start` and check if you see additional error in the terminal.

Also, have you run the migrations before starting the app?

**Comment by specked** [comment]
I'm running the docker through Unraid.
https://github.com/imagegenius/docker-ai-chat-app

I'm not sure how to do what you've asked. When I tried:

`root@e6d1ac16b72a:/usr/lib/node_modules/corepack/shims# ./yarn dev
yarn run v1.22.19
warning ../../../../package.json: No license field
error Command "dev" not found.`

Thank you

**Comment by jimzer** [comment]
> > 
> 
> 
> 
> Now it's working fine! God job man!

Thanks for letting me know 😄

**Comment by jimzer** [comment]
@specked can you retry with the new app version? 

Try rebuilding it from scratch. It seems to have worked for @RyzerZ

**Comment by specked** [comment]
my issue is duplicated here: https://github.com/bitswired/ai-chat-app/issues/5 feel free to close this one
